name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata and set tags
        id: meta
        run: |
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG_SHA=$IMAGE_NAME:$SHORT_SHA" >> $GITHUB_ENV
          echo "TAG_LATEST=$IMAGE_NAME:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.TAG_SHA }} .
          if [ "${{ github.event.workflow_run.head_branch }}" == "main" ]; then
            docker tag ${{ env.TAG_SHA }} ${{ env.TAG_LATEST }}
          fi

      - name: Push Docker images
        run: |
          docker push ${{ env.TAG_SHA }}
          if [ "${{ github.event.workflow_run.head_branch }}" == "main" ]; then
            docker push ${{ env.TAG_LATEST }}
          fi
